version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pnbot123
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: "minio_access_key"
      MINIO_ROOT_PASSWORD: "minio_secret_key"
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
    ports:
      - "9010:9000"
      - "9011:9001"
    command: minio server /data --console-address ":9001"
    volumes:
      - storage:/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  storage: